### ISSUE TITLE
Preview | Copy-Paste don't WORK

### ISSUE THREAD

**Issue by timo1050** [mircearoata/SatisfactoryAreaActions#44] opened 2021-05-18 16:02 UTC
![image](https://user-images.githubusercontent.com/8901731/118685122-1ca63780-b803-11eb-8036-5db919843a61.png)
![image](https://user-images.githubusercontent.com/8901731/118685158-24fe7280-b803-11eb-94d8-d8bbef0f90fb.png)
When we use : paste to location, we see the building. Click preview erase the preview :/. Paste the building don't work.

**Comment by tenesto** [comment] 2021-10-03 09:44
i encounter the exact same. Is there any chance this will be fixed? i also tried the "beta" stuff on trello, but i only find a u3 "version" in your zipfiles even the "instructions" says i have to choose u4...

**Comment by mircearoata** [comment] 2021-10-04 04:59
The issue is that it somehow sets the offsets (which are displayed in meters) in centimeters (the UE unit), so the buildings are pasted very far away. You can cut the last 2 digits and preview again and it should bring them back.

And about the beta, all the versions are for Update 4 except for that Update 3 one. I will update the instructions.

**Comment by tenesto** [comment] 2021-10-04 09:53
Hi, thanks for your reply!! realy glad. dont know the "state" of mod devs for this game like Factorio for example ^^

it worked like a charm. thanks for the tipp. (@edit. ok, i wasnt looking inside my pasted building. there are a lot of stuff missing. pipes, belts, power lines... xD thats bad xD)
so if i pasted earlier very far away and i tested like an idiot, is there a place on my map where a lot of buildings stack up? xD
or is it just not pasted cause its "out of boundries" or stuff like that? ^^

anyway. thank u very much for the tipp. i can now copy and paste. i needed that. its hard from factorio blueprints to.... nothing... thanks for the mod.

**### FINAL EDIT** ok, i have to stop here. realy. the normal version doesnt copy belts, lines, pipes and so on and the beta version crashes when i click on "copy" or "fill".
so nothing of them both i cant use :/ have to wait for u to update or whatever.

[crash.txt](https://github.com/mircearoata/SatisfactoryAreaActions/files/7277469/crash.txt)



Area 1.6.5
CL#163716

**Comment by mircearoata** [comment] 2021-10-04 12:29
Yes, they are still pasted, there's no check for out of bounds, but you might be able to see and delete them on the Satisfactory Calculator interactive map.

I haven't seen this crash before, is this with the latest beta (beta 3)?

**Comment by tenesto** [comment] 2021-10-04 12:32
yes. Beta3. Its weird. if i click the first time on Copy or Fill, there is a little flash of text i think on the top left. if i click again. it crashes.  easy replicate is to just rightclick (open area menu) and double click on copy.

@edit i tested again. i think its happening if a "error" occured. if i copy only one foundation, its fine. if i copy more stuff that is connected to the "outside" and your message about that is comming up, the next click on copy is a crash. ok. so i can "avoid" this crash when i see the message "stuff outside connected bla bla bla" i dont click on copy again (or fill) xD
i tried to catch the flashing text: https://gyazo.com/246c79fa9b58e783b9d8aae938f516c2
guess its the same on the right side of the screen ^^
ill test a bit what i can realy copy and what not. maybe i find a way to make a use of it ^^
@edit2 yes, defnitly crash when the error is there with outside connection and i click on copy again. tested a miner area and coal-generator area after i deleted all "outside connections" and it worked. if i put for example the powerline or miner itself back in, i get your message and on a click again i crash.


and yes, i found some buildings with the interactive map xD


@FINAL for today:
Awesome. Now i had time to realy check on my real map and it works like a charm. Even my RSS Signs are perfect copies.
now that i understand how i have to use the mod, its perfekt so far :*

**Closed as completed** 2021-10-08 19:12 UTC
